Added three enemy AI functions
Tupelov/Atlus-Library pull request #7
Opened 2021-03-18 16:26 UTC by Phoenix-neat

2021-03-20 21:03 UTC, Tupelov requested changes
Found some issues with naming consistency.

2021-03-20 21:03 UTC, Tupelov commented on Persona3FES/Modules/Common/Functions.json
> +        "Name": "PARTY_CHECK",
Change this to something like AI_CHK_PARTY

2021-03-20 21:03 UTC, Tupelov commented on Persona3FES/Modules/Common/Functions.json
> +        "Name": "PARTY_CHECK",
This might be AI_CHK_PLAYER_ID

2021-03-20 21:03 UTC, Tupelov commented on Persona3FES/Modules/Common/Functions.json
> +        "Name": "AI_ACT_SKILL_WITH_PERSONA",
Maybe AI_ACT_PERSONA would be a better name

2021-04-04 00:47 UTC, Phoenix-neat commented
let's do it again

2021-04-04 02:31 UTC, Tupelov requested changes

2021-04-04 02:31 UTC, Tupelov commented on Persona3FES/Modules/Common/Functions.json
> +        "Name": "AI_CHK_PLAYER_ID",
Perhaps we could investigate which ID corresponds to which party member so we could create an enum.

2021-04-04 02:31 UTC, Tupelov commented on Persona3FES/Modules/Common/Functions.json
>          "Description": "First value is Persona, second value is Skill",
This should go under the parameter descriptions, not the function itself

2021-04-04 02:31 UTC, Tupelov commented on Persona3FES/Modules/Common/Functions.json
> +        "Name": "AI_CHK_PLAYER_ID",
Not important though

2021-04-04 02:34 UTC, Tupelov requested changes
Needs param names as well.

2021-04-04 02:34 UTC, Tupelov commented on Persona3FES/Modules/Common/Functions.json
>          "Parameters":
Add param names

2021-04-04 02:34 UTC, Tupelov commented on Persona3FES/Modules/Common/Functions.json
>          "Parameters":
Add param names

2021-05-01 12:08 UTC, Tupelov requested changes
Almost ready just needs one thing

2021-05-01 12:08 UTC, Tupelov commented on Persona3FES/Modules/Common/Functions.json
> +        "Name": "AI_XXX",
Put AI_0013F

2021-05-02 14:24 UTC, Phoenix-neat commented
yeah

2021-05-08 23:35 UTC, merged